### ISSUE TITLE
Microphone access denied, and there's now way to allow it

### ISSUE THREAD

**Issue by Alex2002ita** [khlam/discord-sandboxed#14]
For some reason access to the microphone is denied by default and there's no way to allow it, even though it gets recognized by Discord
Happens with both stable and Nightly builds

**Comment by Alex2002ita** [comment]
It seems that the reason why there's no microphone access is because the sandbox never allows Discord to use the mic due to the fact that the function in the file main.js that tells whether or not you're in a voice chat is broken (probably due to a Discord update) and it can't tell if you're in a call and so temporarily give Discord mic access.
The only workaround I found so far is to set the value isConnected from true to false in the line n.296 " if (permission === 'media' && isConnected === true) ", so that the sandbox always gives mic access to Discord both if you're in a call or not

Either the entire function needs to be fixed or it has to be removed completely

**Comment by khlam** [comment]
Should now be fixed in e3953a1686fc71961b0eafd5fc168a6a1686592c

**Comment by Alex2002ita** [comment]
I've to reopen this issue because the new Discord update (that brought the general rebrand that everyone's not liking at all) broke the mic permission function again, just like last time
