### ISSUE TITLE
I don't know how to explain this

### ISSUE THREAD

**Issue by PhoenixDiscord** [khlam/discord-sandboxed#2]
I guess that's left from debugging. Is there a way to remove this?

![Screenshot from 2020-07-05 11-57-43](https://user-images.githubusercontent.com/37777903/86530173-0242c400-bea6-11ea-9460-8218b854024f.png)

**Comment by khlam** [comment]
addressed in a27cff76f0e88d8784f9c25b703bbf8b8414be88
