### ISSUE TITLE
MacOs and Linux version?

### ISSUE THREAD

**Issue by HkopMD** [khlam/discord-sandboxed#23]
Are there coming a MacOs and linux version

**Comment by CardboardTurtle** [comment]
bump

**Comment by khlam** [comment]
Hi all, thanks for your interest! 

The project will run on MacOS and Linux distributions that can install node and compile from source.

1) I don't have an apple device to test on, so I'm not going to upload a pre-compiled binary to release I can't validate or build. GitHub actions may support this but I don't have the time to investigate. Forks and pull requests are welcome if someone figures that out! 

2) I do not use voice or the push-to-talk functionality on Linux (Debian & Manjaro) and I suspect it does not work. I don't have time to figure that out, so like 1) I'm not going to upload a pre-compiled binary to release that isn't fully featured. Again, forks and pull requests are welcome!

On Linux, the command `npm run package-AppImage` (which was added a long time ago) should produce an AppImage.
