### ISSUE TITLE
Push to talk on Dev branch broken

### ISSUE THREAD

**Issue by khlam** [khlam/discord-sandboxed#30]
Hello all, I'm suspecting the push to talk feature is broken, it seems to have stopped working for me. 

If you are able to run the nightly release (this one:https://github.com/khlam/discord-sandboxed/releases/tag/1.1.7-nightly) and you are able to use the push to talk feature, can you please share your OS information and "config.json" (push to talk configuration)?

On Windows this is found under C:\Users\<your username>\Documents\DiscordSandbox

thank you.

**Comment by Zereges** [comment]
Push to talk never worked for me (except for 5 minutes of random restarting, reconfiguring both sandbox and discord itself, trying different keys, etc.)

I am running `Windows 10 Education 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)` and config is just

```
{
  "pttDevice": "keyboard",
  "key": 52,
  "delay": "250"
}
```

**Comment by Zereges** [comment]
Ok, gave it a try and push to talk works on the dev branch :)
