### ISSUE TITLE
Bot interactions don't work

### ISSUE THREAD

**Issue by TheLounger** [khlam/discord-sandboxed#33]
I run my own bot that uses [Interactions](https://discord.com/developers/docs/interactions/receiving-and-responding), this works fine on regular Discord and Discord in Firefox.
On Discord Sandboxed however, the client immediately fails with `This interaction failed` and the interaction never reaches the bot.

**Comment by khlam** [comment]
Fixed in 111d994a6e101a0059aa2944485bdf15ad128b1d
