### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lvl4Sword** [khlam/discord-sandboxed#38]
I looked at the readme and had a question.
Would you recommend using this project as opposed to just running Discord within a browser window?
I'm curious as to your response. Thanks.

**Comment by khlam** [comment]
I like using push-to-talk so that's why I made this. If I used voice-activation then I would just use Discord in the browser. I think  ublock origin will block Discord's telemetry calls.
Electron/nodejs has a lot of downsides, constant security vulnerabilities, non-free code, etc.
