### ISSUE TITLE
2FA doesn't work

### ISSUE THREAD

**Issue by EdricTruong** [khlam/discord-sandboxed#9]

**Comment by m2jest1c** [comment]
Having this issue right now. "A network error has occurred". Token login using console also doesn't work. Any idea what I can do?

**Comment by KhanTyranus** [comment]
> 
> 
> Having this issue right now. "A network error has occurred". Token login using console also doesn't work. Any idea on what I can do?

Just resolved this with a the latest PR, still need to build it for the releases page, also added fixes for gifs with this PR.
